version: "3"

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: jce-janusgraph-1
    ports:
      - "8182:8182"
    networks:
      - jce-network-1
    volumes:
      # bind mounts for configs; use read only so not overridden by environment variables
      - "./conf:/etc/opt/janusgraph/:ro"
    #    healthcheck:
    #      test: ["CMD", "bin/gremlin.sh", "-e", "scripts/remote-connect.groovy"]
    #      interval: 10s
    #      timeout: 30s
    #      retries: 3
    environment:
      janusgraph.storage.hostname: jce-cassandra
      janusgraph.index.search.hostname: jce-elastic
  cassandra:
    image: cassandra:3
    container_name: jce-cassandra
    #    volumes:
    #      - ./data:/var/lib/cassandra
    ports:
      - "9042:9042"
      - "9160:9160"
    networks:
      - jce-network-1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: jce-elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "cluster.name=docker-cluster"
      - "transport.host=127.0.0.1"
      - "discovery.zen.minimum_master_nodes=1"
      - "xpack.security.enabled=false"

    ports:
      - "9200:9200"
    networks:
      - jce-network-1
networks:
  jce-network-1: